/* One-off: inline bloxie.svg into a React component with animatable eye groups. */
const fs = require('fs');
const path = require('path');

const svgPath = path.join(__dirname, '../public/assets/decorations/bloxie.svg');
const outPath = path.join(__dirname, '../src/components/ui/BloxieCharacter.tsx');

const src = fs.readFileSync(svgPath, 'utf8');
const openTag = src.match(/<svg[^>]*>/)[0];
const viewBox = (openTag.match(/viewBox="([^"]+)"/) || [])[1] || '0 0 630 579';

let inner = src.slice(src.indexOf(openTag) + openTag.length, src.lastIndexOf('</svg>'));

// hyphenated SVG attrs -> JSX camelCase
inner = inner
  .replace(/clip-path=/g, 'clipPath=')
  .replace(/clip-rule=/g, 'clipRule=')
  .replace(/fill-rule=/g, 'fillRule=')
  .replace(/stroke-width=/g, 'strokeWidth=')
  .replace(/stroke-linejoin=/g, 'strokeLinejoin=')
  .replace(/stroke-linecap=/g, 'strokeLinecap=');

// Wrap eye white+pupil+highlights (paths 6..9) and pupil+highlights (7..9)
let i = 0;
inner = inner.replace(/<path\s+d="[^"]+"\s*fill="[^"]+"\s*\/?>/g, (m) => {
  const idx = i++;
  if (idx === 6) return '<g className="bloxie-eye">' + m;
  if (idx === 7) return '<g className="bloxie-pupil">' + m;
  if (idx === 9) return m + '</g></g>';
  return m;
});

const header = [
  '/**',
  ' * Bloxie as inline SVG so his eye can be animated (blink + look around).',
  ' * Generated by scripts/gen-bloxie.cjs from public/assets/decorations/bloxie.svg.',
  ' * The eye white, pupil and highlights sit in .bloxie-eye / .bloxie-pupil groups.',
  ' */',
  "export function BloxieCharacter({ className = '' }: { className?: string }) {",
  '  return (',
  '    <svg viewBox="' + viewBox + '" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">',
].join('\n');

const footer = ['    </svg>', '  );', '}', ''].join('\n');

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, header + '\n' + inner.trim() + '\n' + footer);

console.log('paths processed:', i);
console.log('eye group:', /bloxie-eye/.test(inner), '| pupil group:', /bloxie-pupil/.test(inner));
console.log('wrote', outPath);
